### ISSUE TITLE
Ponder and/or FRC?

### ISSUE THREAD

**Issue by CMCanavessi** [mhonert/velvet-chess#1]
Hi, great to see progress on the engine! It's almost "TCEC Ready" with the NNUE strength. Do you have plans to implement ponder and/or FRC support?

**Comment by microsmeta** [comment]
Hi Martin!
Congratulations and thanks for Velvet 3.0.0. I have just started to test it in my SuperBlitz: https://www.chess.com/forum/view/game-analysis/freeware-against-commercial-chess-software-arena-3-5-1-vs-chessbase-fritz-17
 
And added your reference here: http://talkchess.com/forum3/viewtopic.php?f=2&t=78182&p=908430#p909451

Best regards, Alex

**Comment by mhonert** [comment]
I just released v3.1.0, which includes pondering support.
FRC will probably be part of one of the next releases.

**Comment by microsmeta** [comment]
OK I try it

**Comment by mhonert** [comment]
I released v3.3.0, which adds support for FRC.

**Comment by CMCanavessi** [comment]
Awesome!

**Comment by microsmeta** [comment]
Thank you Martin, just downloaded and i will test it very soon :-)

Alex
