### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [mhonert/velvet-chess#12]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by mhonert** [comment]
There are no specific optimizations for these instruction sets, but it should already be possible to compile for Android and other devices that use an ARM-based CPU.
What issues did you observe during compilation?

**Comment by mhonert** [comment]
The current main branch now also contains optimizations using Neon intrinsics.
