### ISSUE TITLE
Windows Defender on Windows 11 ARM64 detect Velvet v3.0.0  popcount sse41.exe as a Trojan!

### ISSUE THREAD

**Issue by microsmeta** [mhonert/velvet-chess#4]
![virus](https://user-images.githubusercontent.com/8478683/139835626-8c62921a-79e3-4e69-ab85-0b14116fc398.png)

Martin I know that it is a false positive, but I must allow it to play games, please fix it :-)

https://www.chess.com/forum/view/game-analysis/freeware-against-commercial-chess-software-arena-3-5-1-vs-chessbase-fritz-17

**Comment by mhonert** [comment]
Thanks for the report.
I will see, what I can do about it. Previous versions of Velvet did not have this issue.
Velvet V3 is build with a new Rust version, which was upgraded to LLVM 13. Perhaps this new version generates "unusual" patterns in the executable, which trigger some heuristics in antivirus scanners.

**Comment by microsmeta** [comment]
Windows Defender now doesn't even allow to add velvet 3.0.0 popcnt sse4.2 to aooroved apps. Now using nopopop exe added to approved apps before launching. Please try to fix it.

**Comment by mhonert** [comment]
I just released a new minor release version, where I switched to Rust v1.56.1.
As far as I can see, this has solved the false positive detections.
