### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by archimedeschess** [mhonert/velvet-chess#6]
When cross compiling to Android with the following command
`cargo build --release --bin velvet --target=aarch64-linux-android`
I get the following error messages (version 5.0.0 still worked):

> warning: In file included from fathom/src/tbprobe.c:50:
warning: /usr/include/pthread.h:681:6: error: 'regparm' is not valid on this platform
warning:      __cleanup_fct_attribute;
warning:      ^~~~~~~~~~~~~~~~~~~~~~~
warning: /usr/include/bits/pthreadtypes.h:255:50: note: expanded from macro '__cleanup_fct_attribute'
warning: # define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
warning:                                                  ^            ~
warning: In file included from fathom/src/tbprobe.c:50:
warning: /usr/include/pthread.h:693:3: error: 'regparm' is not valid on this platform
warning:   __cleanup_fct_attribute;
warning:   ^~~~~~~~~~~~~~~~~~~~~~~
warning: /usr/include/bits/pthreadtypes.h:255:50: note: expanded from macro '__cleanup_fct_attribute'
warning: # define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
warning:                                                  ^            ~
warning: In file included from fathom/src/tbprobe.c:50:
warning: /usr/include/pthread.h:734:6: error: 'regparm' is not valid on this platform
warning:      __cleanup_fct_attribute __attribute__ ((__noreturn__))
warning:      ^~~~~~~~~~~~~~~~~~~~~~~
warning: /usr/include/bits/pthreadtypes.h:255:50: note: expanded from macro '__cleanup_fct_attribute'
warning: # define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))
warning:                                                  ^            ~
warning: fathom/src/tbprobe.c:247:10: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
warning:   return bswap64(input);
warning:          ^
warning: fathom/src/stdendian.h:86:33: note: expanded from macro 'bswap64'
warning: #define bswap64(x)              bswap_64(x)
warning:                                 ^
warning: /usr/include/byteswap.h:37:21: note: expanded from macro 'bswap_64'
warning: #define bswap_64(x) __bswap_64 (x)
warning:                     ^
warning: /usr/include/bits/byteswap.h:132:20: note: expanded from macro '__bswap_64'
warning:              __r.__l[0] = __bswap_32 (__w.__l[1]);                            \
warning:                           ^
warning: /usr/include/bits/byteswap.h:76:16: note: expanded from macro '__bswap_32'
warning:                      : "=r" (__v)                                             \
warning:                              ^
warning: fathom/src/tbprobe.c:247:10: note: use constraint modifier "w"
warning: fathom/src/stdendian.h:86:33: note: expanded from macro 'bswap64'
warning: #define bswap64(x)              bswap_64(x)
warning:                                 ^
warning: /usr/include/byteswap.h:37:21: note: expanded from macro 'bswap_64'
warning: #define bswap_64(x) __bswap_64 (x)
warning:                     ^
warning: /usr/include/bits/byteswap.h:132:20: note: expanded from macro '__bswap_64'
warning:              __r.__l[0] = __bswap_32 (__w.__l[1]);                            \
warning:                           ^
warning: /usr/include/bits/byteswap.h:74:19: note: expanded from macro '__bswap_32'
warning:                      "rorl $16, %0;"                                          \
warning:                                 ^
warning: fathom/src/tbprobe.c:247:10: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
warning:   return bswap64(input);
warning:          ^
warning: fathom/src/stdendian.h:86:33: note: expanded from macro 'bswap64'
warning: #define bswap64(x)              bswap_64(x)
warning:                                 ^
warning: /usr/include/byteswap.h:37:21: note: expanded from macro 'bswap_64'
warning: #define bswap_64(x) __bswap_64 (x)
warning:                     ^
warning: /usr/include/bits/byteswap.h:133:20: note: expanded from macro '__bswap_64'
warning:              __r.__l[1] = __bswap_32 (__w.__l[0]);                            \
warning:                           ^
warning: /usr/include/bits/byteswap.h:76:16: note: expanded from macro '__bswap_32'
warning:                      : "=r" (__v)                                             \
warning:                              ^
warning: fathom/src/tbprobe.c:247:10: note: use constraint modifier "w"
warning: fathom/src/stdendian.h:86:33: note: expanded from macro 'bswap64'
warning: #define bswap64(x)              bswap_64(x)
warning:                                 ^
warning: /usr/include/byteswap.h:37:21: note: expanded from macro 'bswap_64'
warning: #define bswap_64(x) __bswap_64 (x)
warning:                     ^
warning: /usr/include/bits/byteswap.h:133:20: note: expanded from macro '__bswap_64'
warning:              __r.__l[1] = __bswap_32 (__w.__l[0]);                            \
warning:                           ^
warning: /usr/include/bits/byteswap.h:74:19: note: expanded from macro '__bswap_32'
warning:                      "rorl $16, %0;"                                          \
warning:                                 ^
warning: fathom/src/tbprobe.c:251:10: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
warning:   return bswap32(input);
warning:          ^
warning: fathom/src/stdendian.h:85:33: note: expanded from macro 'bswap32'
warning: #define bswap32(x)              bswap_32(x)
warning:                                 ^
warning: /usr/include/byteswap.h:34:21: note: expanded from macro 'bswap_32'
warning: #define bswap_32(x) __bswap_32 (x)
warning:                     ^
warning: /usr/include/bits/byteswap.h:76:16: note: expanded from macro '__bswap_32'
warning:                      : "=r" (__v)                                             \
warning:                              ^
warning: fathom/src/tbprobe.c:251:10: note: use constraint modifier "w"
warning: fathom/src/stdendian.h:85:33: note: expanded from macro 'bswap32'
warning: #define bswap32(x)              bswap_32(x)
warning:                                 ^
warning: /usr/include/byteswap.h:34:21: note: expanded from macro 'bswap_32'
warning: #define bswap_32(x) __bswap_32 (x)
warning:                     ^
warning: /usr/include/bits/byteswap.h:74:19: note: expanded from macro '__bswap_32'
warning:                      "rorl $16, %0;"                                          \
warning:                                 ^
warning: fathom/src/tbprobe.c:1605:12: warning: cast to 'uint8_t *' (aka 'unsigned char *') from smaller integer type 'unsigned int' [-Wint-to-pointer-cast]
warning:     data = (uint8_t *)(((uintptr_t)data + 0x3f) & ~0x3f);
warning:            ^
warning: fathom/src/tbprobe.c:1609:14: warning: cast to 'uint8_t *' (aka 'unsigned char *') from smaller integer type 'unsigned int' [-Wint-to-pointer-cast]
warning:       data = (uint8_t *)(((uintptr_t)data + 0x3f) & ~0x3f);
warning:              ^
warning: fathom/src/tbprobe.c:2459:41: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
warning:   if (popcount(pos->white | pos->black) <= cardinalityDTM) {
warning:       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
warning: 6 warnings and 3 errors generated.

**Comment by mhonert** [comment]
Thanks for the issue report and your interest in Velvet.
v5.1.0 integrates the Fathom library for Syzygy tablebase support.
It seems, that it is not compatible with the aarch64-linux-android target, but I will investigate it a bit more.

As a workaround I made the tablebase feature optional.
You can now set the flag `--no-default-features` in the `cargo build` command (see also the updated README).

Note: this currently only works on the master branch (currently v5.2.0-dev1).
If you specifically need a build for v5.1.x, then I could backport the workaround.
But currently the changes between v5.2.0-dev1 and v5.1.0 are minimal and for the most part are related to the tablebase logic.

**Comment by archimedeschess** [comment]
Thank you very much. It works.

**Comment by Frosty54** [comment]
Hi, Mr Archimedes. Thank you for great work on sourceforge. Can you update this chess engines please. Thanks. https://github.com/vshcherbyna/igel/releases
https://github.com/dsekercioglu/blackmarlin/releases
P.S. Archimedes, is it possible to compile Charisma (Stockfish clone)

**Comment by Frosty54** [comment]
https://chessengines.blogspot.com/2022/12/chess-engine-charisma-stockfish-clone.html?m=1
Here is sources.

**Comment by Frosty54** [comment]
https://chessengines.blogspot.com/2023/01/chess-engine-charisma-saphir-stockfish.html?m=1
Correct link.

**Comment by Frosty54** [comment]
@mhonert sorry me for posting this here
